name: Android CI to JCenter
on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew install
    - name: Upload to jcenter
      env:
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        BINTRAY_ORG: ${{ secrets.BINTRAY_ORG }}
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      run: ./gradlew bintrayUpload
    - name: Build documentation
      run: ./gradlew :docs:orchidBuild
    - name: set up AWS CLI and deploy docs
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-1
        run: aws s3 sync ./docs/build/ s3://ziwo/android-ziwo-sdk/

