name: Publish to Jcenter
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Verify Java version
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java -version
      - name: Verify Java version
        run: java -version
      - name: Build with Gradle
        run: ./gradlew install
      - name: Upload to jcenter
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          BINTRAY_ORG: ${{ secrets.BINTRAY_ORG }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        run: ./gradlew bintrayUpload
      - name: Build documentation
        run: ./gradlew :docs:orchidBuild
